env:
  browser: true
  es6: true
extends: [
  "eslint:recommended",
  "plugin:@typescript-eslint/recommended",
]
plugins: ["@typescript-eslint"]
ignorePatterns: [
  "src/stub_files/Female3DCG_Types.d.ts",
  "src/stub_files/Typedef.d.ts",
  "dist/",
]
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: tsconfig.json
rules:
  quotes: [error, double, { avoidEscape: true }]
  indent: [error, 4, { SwitchCase: 1 }]
  semi: [error, always]
  comma-dangle: [error, always-multiline]
  linebreak-style: [error, unix]
  "@typescript-eslint/no-unused-vars": [error, { varsIgnorePattern: "_" }]
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/ban-ts-comment": off
